version: '3'
services:
    hyperf:
        build:
            context: .
        container_name: hyperf
        working_dir: /data/web
        volumes:
            - ../:/data/web
        ports:
            - 9501:9501
        depends_on:
            - mysql
            - redis
    mysql:
        image: mysql:5.6
        platform: linux/x86_64
        container_name: mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        volumes:
          - ./data/redis:/data